---
title: "sari_2022"
author: "Ahmad Tarrabeih"
date: "2024-06-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import libraries, message=FALSE, warning=FALSE}
pacman::p_load(
  here,
  rio,
  data.table,             # fast to load large datasets
  ggplot2,                # data visualization
  crosstable,             # generate tables 
  flextable,              # enhance table visualization
  dplyr,                  # data processing and manipulation  
  maps,                   # draw geographical maps
  mapproj,                # draw geographical maps
  lubridate,              # date manipulation
  incidence,               # epidemiological curve,
  janitor,                # data cleaning + quick tables
  skimr,
  tidyverse,               # data management
  aweek,                  # date to week 
  writexl,
  eeptools
)
```

```{r import sari} 

####### pgm_sari_up 2022
#######
####### from line list use this sari_up_2022_R_RMD_2024_event_final_June_2024 as csv code
#######
#######

sari = import(here("input","sari_2022.csv")) %>% clean_names()
lbn_c = import(here("input","lbn_c.xlsx"))
country_code  = import(here("input","country_code.xlsx"))

 
```

```{r date format}
date_format = "%d/%m/%Y"
```
 
```{r}
#Country
Country = "Lebanon"

# Governorate
sub = substr( sari$organisation_unit_name,1,2)
sub_caza =
ifelse(sub=="AK","Akkar",
ifelse(sub=="AL","Aleyh",
ifelse(sub=="BD","Baabda",
ifelse(sub=="BL","Baalbeck",
ifelse(sub=="BT","Batroun",
ifelse(sub=="BC","Becharreh",
ifelse(sub=="BR","Beirut",
ifelse(sub=="WB","Beqaa Gharby",
ifelse(sub=="BJ","Bint Jbeil",
ifelse(sub=="CH","Chouf",
ifelse(sub=="HS","Hasbaya",
ifelse(sub=="HR","Hermel",
ifelse(sub=="JB","Jbeil",
ifelse(sub=="JZ","Jezzine",
ifelse(sub=="KW","Kesrwan",
ifelse(sub=="KR","Koura",
ifelse(sub=="MR","Marjeoun",
ifelse(sub=="MT","Matn",
ifelse(sub=="MD","Mineh Danieh",
ifelse(sub=="NB","Nabatieh",
ifelse(sub=="RS","Rashaya",
ifelse(sub=="SD","Saida",
ifelse(sub=="SR","Sour",
ifelse(sub=="TR","Tripoli",
ifelse(sub=="ZH","Zahleh",
ifelse(sub=="ZG","Zgharta","UN"))))))))))))))))))))))))))
Governorate = lbn_c$province[ match(sub_caza, lbn_c$caza) ] #match

# Site
Site = substr(sari$organisation_unit_name,1,6) ############################################# Check inactive

# Nationailty
Nationailty = NA

# Gender
Gender = ifelse(sari$de_fl_patient_sex=="1","Male",ifelse(sari$de_fl_patient_sex=="2","Female","Unknown"))

# Telephone
Telephone = NA 

# Address
Address =  NA 

# BirthDate
BirthDate = format(as.Date(substr(sari$de_fl_patient_age, 1, 10), format = "%Y-%m-%d"), date_format)


# AgeYear


# enroll_date <- as.Date(sari$de_fl_specimen_collection_date) 
enroll_date <- substr(as.Date(sari$de_fl_date_onset, format="%Y-%m-%d"),1,10) #de_fl_date_onset
date_of_birth <- substr(as.Date(sari$de_fl_patient_age, format="%Y-%m-%d"),1,10)

# Calculate the interval between the dates
interval <- interval(date_of_birth, enroll_date)

# Convert the interval to a period
period <- as.period(interval)

# Extract the number of years and months
AgeYear <- period@year
AgeMonths <- period@month

# AgeMonths

AgeMonths[AgeMonths<0] = NA
AgeYear[AgeYear<0] = NA

AgeMonths = ifelse( (AgeMonths=="0" | is.na(AgeMonths) | AgeMonths=="" ) & (AgeYear=="0"  | AgeYear==0), "1",AgeMonths)
view(table(AgeMonths, useNA = "always"))


# AddressGovernorate
AddressGovernorate = lbn_c$province[ match(sari$de_fl_patient_caza_residence, lbn_c$caza_code) ]

# District
District = lbn_c$caza[ match(sari$de_fl_patient_caza_residence, lbn_c$caza_code) ]


# FirstInterviewDate
# FirstInterviewDate =  format(as.Date(substr(sari$de_fl_specimen_collection_date, 1, 10), format = "%Y-%m-%d"), date_format)
FirstInterviewDate = NA #By Amir

# AdmissionDate
AdmissionDate = format(as.Date(substr(sari$de_fl_hospital_admission_date, 1, 10), format = "%Y-%m-%d"), date_format)

# SymptomOnsetDate
SymptomOnsetDate = format(as.Date(substr(sari$de_fl_date_onset, 1, 10), format = "%Y-%m-%d"), date_format)


# HospitalId
HospitalId = sari$de_fl_id_number

# OutcomeDate
OutcomeDate= format(as.Date(substr(sari$de_fl_discharge_date, 1, 10), format = "%Y-%m-%d"), date_format)

# Outcome
Outcome = ifelse(sari$de_fl_discharge_status=="1", "Discharge",ifelse(sari$de_fl_discharge_status=="2","Transfer",ifelse(sari$de_fl_discharge_status=="3","Death",ifelse(sari$de_fl_discharge_status=="9","Unknown",NA))))


# Temperature
Temperature = ifelse(sari$de_fl_fever_c>43 | sari$de_fl_fever_c<35,NA,sari$de_fl_fever_c) #fever between 35 and 43


# Ventilation
Ventilation = case_when(
  sari$de_fl_mechanical_ventilation == "0" ~ "No",
  sari$de_fl_mechanical_ventilation == "1" ~ "Yes",
  sari$de_fl_mechanical_ventilation == "2" ~ "Yes",
    sari$de_fl_mechanical_ventilation == "9" ~ NA,
    TRUE ~ NA_character_  # Set default value to NA
  ) 

# ICUAddmission
ICUAddmission =ifelse(sari$de_fl_ward=="3","Yes","No")

# AdmissionWard
AdmissionWard = case_when(
  sari$de_fl_ward == "1" ~ "internal medicine",
  sari$de_fl_ward == "2" ~ "pediatrics",
  sari$de_fl_ward == "3" ~ "intensive care unit",
  sari$de_fl_ward == "4" ~ "gyneco obstetrics",
  sari$de_fl_ward == "5" ~ "other",
  sari$de_fl_ward == "9" ~ "unspecified",
  TRUE~NA
) #### 
  

# Pregnancy
Pregnancy =  ifelse(sari$de_fl_patient_sex == 1, NA, 
                    ifelse(sari$de_fl_patient_sex == 2, sari$de_fl_pregnancy, "No"))
 
 Pregnancy = ifelse(Pregnancy=="1","Yes","No")
 
# VaccinationForInfluenzaLast6months
 VaccinationForInfluenzaLast6months = ifelse(sari$de_fl_vaccination_flu==1 ,"Yes", ifelse(sari$de_fl_vaccination_flu==0,"No","Unknown"))
 
# ReceiveInfluenzaAntiviralDrugsLast14days
 ReceiveInfluenzaAntiviralDrugsLast14days = ifelse(sari$de_fl_antiviral_treatement==1 ,"Yes", ifelse(sari$de_fl_antiviral_treatement==0,"No","Unknown"))
 
# ChronicMedicalConditions (Comma Seperated)
 sari$de_fl_chronic_respiratory_diseases[sari$de_fl_chronic_respiratory_diseases == 1] <- "Chronic lung disease,"
sari$de_fl_chronic_cardiac_diseases[sari$de_fl_chronic_cardiac_diseases == 1] <- "Heart disease,"
sari$de_fl_diabetes[sari$de_fl_diabetes == 1] <- "Diabetes,"
sari$de_fl_chronic_liver_diseases[sari$de_fl_chronic_liver_diseases == 1] <- "Chronic liver disease,"
sari$de_fl_chronic_kidney_diseases[sari$de_fl_chronic_kidney_diseases == 1] <- "Chronic kidney disease,"
sari$de_fl_chronic_hematological_disorders[sari$de_fl_chronic_hematological_disorders == 1] <- "Chronic hematological disorder,"
sari$de_fl_neuromuscular_dysfunction[sari$de_fl_neuromuscular_dysfunction == 1] <- "Neuromuscular dysfunction,"
sari$de_fl_immuno_compromised[sari$de_fl_immuno_compromised == 1] <- "Immune compromised,"
sari$de_fl_other_diseases[sari$de_fl_other_diseases == 1] <- "Other,"

# Combine strings into one
ChronicMedicalConditions <- paste(sari$de_fl_chronic_respiratory_diseases,
                                                      sari$de_fl_chronic_cardiac_diseases,
                                                      sari$de_fl_diabetes,
                                                      sari$de_fl_chronic_liver_diseases,
                                                      sari$de_fl_chronic_kidney_diseases,
                                                      sari$de_fl_chronic_hematological_disorders,
                                                      sari$de_fl_neuromuscular_dysfunction,
                                                      sari$de_fl_immuno_compromised,
                                                      sari$de_fl_other_diseases, sep = "")

# Remove NA and 0 from the string
ChronicMedicalConditions <- gsub("NA", "", ChronicMedicalConditions)
ChronicMedicalConditions <- gsub("0", "", ChronicMedicalConditions)
ChronicMedicalConditions <- sub(",\\s*$", "", ChronicMedicalConditions)  
ChronicMedicalConditions[ChronicMedicalConditions == ""] = NA
# view(table(ChronicMedicalConditions, useNA = "always"))


# Lab_DateSpecimenCollected
 Lab_DateSpecimenCollected = format(as.Date(substr(sari$de_fl_specimen_collection_date, 1, 10), format = "%Y-%m-%d"), date_format)

# Lab_DateOfShipment
Lab_DateOfShipment = format(as.Date(substr(sari$de_fl_date_reception_specimen, 1, 10), format = "%Y-%m-%d"), date_format)


# Lab_DateLabReceivedSpecimen
Lab_DateLabReceivedSpecimen= format(as.Date(substr(sari$de_fl_date_reception_specimen, 1, 10), format = "%Y-%m-%d"), date_format)

# Lab_OropharyngealSpecimen
Lab_OropharyngealSpecimen = ifelse(sari$de_fl_specimen_type=="2","Yes","No")

# Lab_NasopharyngealSpecimen
Lab_NasopharyngealSpecimen = ifelse(sari$de_fl_specimen_type=="1","Yes","No")

# Lab_BloodSpecimen 
Lab_BloodSpecimen = NA

# Lab_SpecimenOther
Lab_SpecimenOther= ifelse(sari$de_fl_specimen_type=="1","Yes","No")


# Lab_DateResultsReported
Lab_DateResultsReported = format(as.Date(substr(sari$de_fl_date_pcr_result, 1, 10), format = "%Y-%m-%d"), date_format)

# Lab_Comments
Lab_Comments = NA


# LabResult
influ = recode(
  sari$de_fl_pcr_result_influenza, 
  "20" = "influenza: a",
  "21" = "Influenza: ah1",
  "41" = "influenza: ah1+ah3",
  "23" = "influenza: ah3",
  "24" = "influenza: ah5",
  "25" = "influenza: ah7",
  "30" = "influenza: b",
  "31" = "influenza: b yamagata",
  "32" = "influenza: b victoria",
  "10" = "Negative",
  "11" = "Not tested",
  .default = NA_character_ 
)


covid <- recode(
  sari$de_fl_pcr_result_covid,
  '0' = '0_negative',
  '1' = '1_positive',
  '9' = '9_not_processed',
  .default = NA_character_
)

rsv  = recode(
  sari$de_fl_pcr_rsv_classification,
  "0" = "0_negative",
  "1" = "1_positive",
  "9" = "9_not processed",
  .default = NA_character_
)

LabResult <- ifelse(
  rsv %in% c("1_positive") |
    covid %in% c("1_positive") |
    influ %in% c(
      "influenza: a", "Influenza: ah1", "influenza: ah3", "influenza: ah5",
      "influenza: ah7", "influenza: b", "influenza: b yamagata",
      "influenza: b victoria", "influenza: ah1+ah3", "Other"
    ), "Positive",
  ifelse(
    (influ == "Negative" & covid == "0_negative") | rsv != "1_positive",
    "Negative",
    ifelse(
      influ == "Not tested" & covid == "9_not processed" & rsv == "9_not processed",
      "Not tested",
      NA
    )
  )
)


# PositiveViruses (Comma Seperated)
influ = recode(
  sari$de_fl_pcr_result_influenza, 
  "20" = "Not-subtyped",
  "21" = "(H1N1)pdm009",
  "41" = "Mixed",
  "23" = "(H3N2)",
  "24" = "(H5N1)",
  "25" = "influenza: ah7",
  "30" = "Lineage not determined",
  "31" = "Yamagata lineage",
  "32" = "Victoria lineage",
  "10" = "Negative",
  "11" = "Not tested",
  .default = NA_character_ 
)

influ[influ==11] = NA # not processed 
influ[influ==10] = NA # negative
influ[influ==25] = NA # old not found in main list

PositiveViruses = character(nrow(sari))

  for (i in 1:nrow(sari) ){
    tested_virus_list <- character()
    
    if (LabResult[i] == "Positive" && !is.na(influ[i]) && influ[i] != "Not tested" && influ[i] != "Negative") {
      tested_virus_list <- c(tested_virus_list, influ[i])
    }
    
    if (LabResult[i] == "Positive" && !is.na(covid[i]) && covid[i]  == "1_positive") {
      tested_virus_list <- c(tested_virus_list, "COVID-19") 
    }
    
    if (LabResult[i] == "Positive" && !is.na(rsv[i]) && rsv[i] == "1_positive") {
      tested_virus_list <- c(tested_virus_list, "RSV")
    }
    PositiveViruses[i] <- paste(tested_virus_list, collapse = ",")  
    
  }
PositiveViruses[PositiveViruses==""] = NA

# HistoryTravel
HistoryTravel = ifelse(sari$de_fl_travel_history_21d=="1","Yes",ifelse(sari$de_fl_Travel_History_21d=="0","No",NA))

# HistoryTravel_Where
HistoryTravel_Where = country_code$Country[ match( sari$de_fl_country_visited,country_code$Alpha_3_code) ]
 
HistoryTravel_Where[HistoryTravel_Where == "United Kingdom of Great Britain and Northern Ireland (the)"] = "United Kingdom"
HistoryTravel_Where[HistoryTravel_Where == "United States of America (the)"] = "United States of America"
HistoryTravel_Where[HistoryTravel_Where == "Netherlands (the)"] = "Netherlands"
HistoryTravel_Where[HistoryTravel_Where=="United Arab Emirates (the)"] = "United Arab Emirates"
HistoryTravel_Where[HistoryTravel_Where == "Central African Republic (the)"] = NA # not found in main dictionary
HistoryTravel_Where[HistoryTravel_Where == "Côte d'Ivoire"] = NA # not found in main dictionary
 

# HistoryTravel_When
HistoryTravel_When = NA

# TestedViruses (Comma Seperated)
TestedViruses= ifelse(rsv=="0_negative" | rsv=="1_positive","Not-subtyped, COVID-19,RSV","Not-subtyped,COVID-19")
 
TestedViruses= ifelse((LabResult=="Negative" | LabResult=="Positive") & is.na(rsv),"Not-subtyped,COVID-19",TestedViruses)

influ = recode(
  sari$de_fl_pcr_result_influenza, 
  "20" = "Not-subtyped",
  "21" = "(H1N1)pdm009",
  "41" = "Mixed",
  "23" = "(H3N2)",
  "24" = "(H5N1)",
  "25" = "influenza: ah7",
  "30" = "Lineage not determined",
  "31" = "Yamagata lineage",
  "32" = "Victoria lineage",
  "10" = "Negative",
  "11" = "Not tested",
  .default = NA_character_ 
)



TestedViruses=ifelse(influ %in% c("(H1N1)pdm009", "Mixed", "(H3N2)", "(H5N1)", "Lineage not determined", "Victoria lineage", "Yamagata lineage"),str_replace(TestedViruses,"Not-subtyped", influ), TestedViruses )


# ICUAddmissionDays
ICUAddmissionDays = NA
# VentilationDays
VentilationDays = NA
# DailySmoker
DailySmoker = NA
# NationalId
NationalId = NA
```

```{r}
District <- recode(District, 
   "Matn"="Metn",
   "Beqaa Gharby" = "West Bekaa",
   "Zgharta" = "Zghorta" 
)

District[District=="Unspecified"] = NA
```

```{r}
HistoryTravel_Where[HistoryTravel_Where=="Gabon"] = NA  
HistoryTravel_Where[HistoryTravel_Where=="Netherlands"] = "Netherland" 

 
```

```{r}
final_sari <- data.frame(
Country , 
Governorate , 
Site , 
Nationailty , 
Gender , 
Telephone , 
Address , 
BirthDate , 
AgeYear , 
AgeMonths , 
AddressGovernorate , 
District , 
FirstInterviewDate , 
AdmissionDate , 
SymptomOnsetDate , 
HospitalId , 
OutcomeDate , 
Outcome , 
Temperature , 
Ventilation , 
ICUAddmission , 
AdmissionWard , 
Pregnancy , 
VaccinationForInfluenzaLast6months , 
ReceiveInfluenzaAntiviralDrugsLast14days , 
ChronicMedicalConditions , 
Lab_DateSpecimenCollected , 
Lab_DateOfShipment , 
Lab_DateLabReceivedSpecimen , 
Lab_OropharyngealSpecimen , 
Lab_NasopharyngealSpecimen , 
Lab_BloodSpecimen , 
Lab_SpecimenOther , 
Lab_DateResultsReported , 
Lab_Comments , 
LabResult , 
PositiveViruses, 
HistoryTravel , 
HistoryTravel_Where , 
HistoryTravel_When , 
TestedViruses , 
ICUAddmissionDays , 
VentilationDays , 
DailySmoker , 
NationalId 

)

```

```{r remove not used sites}   
nrow(final_sari)
sites_to_keep_sari <- c("BDH505", "BRH610", "MDH122", "BLH201")

final_sari <- subset(final_sari, Site %in% sites_to_keep_sari)
nrow(final_sari)

final_sari$Governorate[final_sari$Governorate=="Baalbeck - Hermel"] = "Baalbeck-Hermel"  

final_sari$AddressGovernorate[final_sari$AddressGovernorate=="Baalbeck - Hermel"] = "Baalbeck-Hermel" 
final_sari$AddressGovernorate[final_sari$AddressGovernorate=="Unspecified"] = NA


names(final_sari)[names(final_sari) == "ChronicMedicalConditions"] <- "ChronicMedicalConditions (Comma Seperated)"
names(final_sari)[names(final_sari) == "TestedViruses"] <- "TestedViruses (Comma Seperated)"
names(final_sari)[names(final_sari) == "PositiveViruses"] <- "PositiveViruses (Comma Seperated)"

```

```{r}

today = Sys.Date()
write_xlsx(final_sari, path = here("output", paste0("sari_up_2022_final_", today, "_update.xlsx")))
```

